### ISSUE TITLE
Question: Any way to autodetect the language?

### ISSUE THREAD

**Issue by MeinDeutschkurs** [Shakshi3104/LiTeX#3]
It's amazing. Thank you so much for open-sourcing it. I've played around with it a lot and learned from it. Thanks for this.

Unfortunately, there doesn't seem to be a discussion tab, so I'm writing here instead.

Is there any way to automatically detect the language and/or scan for mixed language content? I'm attempting to capture my students' handwritten homework, which often includes descriptions in languages other than German on the same sheet of paper.

Thank you so much,
Johannes

**Comment by Shakshi3104** [comment]
Thanks for the issue!

Sorry, I don't know know how to do that.
But,  I guess Live Text (or [ImageAnalyzer of VisionKit](https://developer.apple.com/documentation/visionkit/imageanalyzer)) automatically determines the language.
If I specify a language [here](https://github.com/Shakshi3104/LiTeX/blob/0352b79c0fc6394a1c34a042a8e96115c410ddc6/LiTeX/LiveTextCLI.swift#L99),  but do not specify it, it will be automatically determined.

**Comment by MeinDeutschkurs** [comment]
Thank you so much for your reply. Sometimes I have mixed language content. Maybe there is any way to check this. I‘ll do a research. Would be great.
