### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by NinjaMooseWMD** [Shakshi3104/LiTeX#5]
This isn't an issue with the program. It's an issue with my own ignorance. 

How do I accomplish step one of the installation?  It says to download the binary file.  Which one is that?  I looked through all the folders and I don't see a file named litex, yet step two says to chmod +x litex then move it to /usr/local/bin.

**Comment by MeinDeutschkurs** [comment]
Under releases?

https://github.com/Shakshi3104/LiTeX/releases

**Comment by NinjaMooseWMD** [comment]
Hahahaha. OMG. I can't believe I overlooked that.  Thank you.
